@startuml tool_usage
left to right direction

title メール送信までの流れ

object "1. 情報準備" as P1
P1 : ・メンバーの名前を記入
P1 : ・自分の署名を記入

object "2. ライブラリインストール" as P2
P2 : ・pandasをいれる

object "3. シフト作成" as P3
P3 : ・自動でシフトを作成
P3 : ・手動でシフトを調整

object "4. メール作成" as P4
P4 : ・自動でメール内容作成
P4 : ・コピペして送信

object "5. メールの定期送信" as P5
P5 : windowsの定期実行に\nsend_mail.batをセットする

P1 --> P2
P2 --> P3
P3 --> P4
P4 --> P5

@enduml